'use strict';

const ROW_COUNT = 50;
const COL_COUNT = 50;
const CELL_WIDTH = 80;
const CELL_HEIGHT = 40;
const COLUMN_HEADER_HEIGHT = 20;
const ROW_HEADER_WIDTH = 40;
const TOOLBAR_HEIGHT = 100;

module.exports = {
    ROW_COUNT,
    COL_COUNT,
    CELL_WIDTH,
    CELL_HEIGHT,
    COLUMN_HEADER_HEIGHT,
    ROW_HEADER_WIDTH,
    TOOLBAR_HEIGHT
};
